// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyDprLjyQHgnIbOpVHKXxP1-UCCwG9GsI',
    appId: '1:287447492369:web:f3b123e83eeb3018490eb0',
    messagingSenderId: '287447492369',
    projectId: 'projetomobile-35311',
    authDomain: 'projetomobile-35311.firebaseapp.com',
    databaseURL: 'https://projetomobile-35311-default-rtdb.firebaseio.com',
    storageBucket: 'projetomobile-35311.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_PnvQdwPrElfmWMD5Gsr-ZfjmBH3WTEc',
    appId: '1:287447492369:android:abfc5107da750cc4490eb0',
    messagingSenderId: '287447492369',
    projectId: 'projetomobile-35311',
    databaseURL: 'https://projetomobile-35311-default-rtdb.firebaseio.com',
    storageBucket: 'projetomobile-35311.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOduRgncisHXWa0SHNvamXcwvgiBBk6l0',
    appId: '1:287447492369:ios:69cbd3c2c356c9c7490eb0',
    messagingSenderId: '287447492369',
    projectId: 'projetomobile-35311',
    databaseURL: 'https://projetomobile-35311-default-rtdb.firebaseio.com',
    storageBucket: 'projetomobile-35311.appspot.com',
    iosClientId: '287447492369-9npjvec737qg32mrpv60ci7dmus9a6g3.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetomobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOduRgncisHXWa0SHNvamXcwvgiBBk6l0',
    appId: '1:287447492369:ios:2a7b7c1fbd8ecac5490eb0',
    messagingSenderId: '287447492369',
    projectId: 'projetomobile-35311',
    databaseURL: 'https://projetomobile-35311-default-rtdb.firebaseio.com',
    storageBucket: 'projetomobile-35311.appspot.com',
    iosClientId: '287447492369-k7ra2dbt25j3bbkj51fbodj84k9r8etq.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetomobile.RunnerTests',
  );
}
